services:
  - type: web
    name: food-donation-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn food_project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: food_project.settings
      - key: PYTHON_VERSION
        value: 3.10
