# Generated by Django 5.2 on 2025-04-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Cooked', 'Cooked'), ('Packaged', 'Packaged'), ('Raw', 'Raw')], max_length=20)),
                ('food_item', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(default='Available', max_length=20)),
            ],
        ),
    ]
